name: Build & SonarCloud Analysis

on:
  push:
      branches: [ "main" ]
  pull_request:
     branches: [ "copyOfMain" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Project
        run: mvn clean verify -DskipTests

      - name: Run Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn sonar:sonar
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ secrets.SONAR_ORG }}
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          -Dsonar.branch.name=${GITHUB_REF_NAME}
          -Dsonar.qualitygate.wait=true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Print Sonar Issues
        if: always()
        run: |
          echo "Branch: ${GITHUB_REF_NAME}"
          curl -u ${{ secrets.SONAR_TOKEN }}: \
            "https://sonarcloud.io/api/issues/search?componentKeys=${{ secrets.SONAR_PROJECT_KEY }}&branch=${GITHUB_REF_NAME}&resolved=false" \
            | jq '.issues[] | {severity, message, component, line}'
